# Generated by Django 3.2.6 on 2021-11-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=35)),
                ('esal', models.IntegerField()),
                ('eadd', models.TextField()),
                ('edate', models.DateField(auto_now_add=True)),
                ('edatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
